--UA Stuff for the lua code
CREATE TABLE C15_REL_CityStateGPLinkage
 (Value TEXT, GreatPersonClassType TEXT DEFAULT 'GREATPERSONCLASS_GENERAL',
  PRIMARY KEY (Value, GreatPersonClassType),
  FOREIGN KEY (Value) REFERENCES TypeProperties  (Value) , 
  FOREIGN KEY (GreatPersonClassType) REFERENCES GreatPersonClasses (GreatPersonClassType));

INSERT INTO C15_REL_CityStateGPLinkage
		(Value, 			GreatPersonClassType)
VALUES	('CULTURAL',		'GREAT_PERSON_CLASS_ARTIST'),
		('CULTURAL',		'GREAT_PERSON_CLASS_WRITER'),
		('CULTURAL',		'GREAT_PERSON_CLASS_MUSICIAN'),
		('MILITARISTIC',	'GREAT_PERSON_CLASS_GENERAL'),
		('MILITARISTIC',	'GREAT_PERSON_CLASS_ADMIRAL'),
		('INDUSTRIAL',		'GREAT_PERSON_CLASS_ENGINEER'),
		('TRADE',			'GREAT_PERSON_CLASS_MERCHANT'),
		('RELIGIOUS',		'GREAT_PERSON_CLASS_PROPHET'),
		('SCIENTIFIC',		'GREAT_PERSON_CLASS_SCIENTIST');